spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employee
    username: employee
    password: employee
  mail:
    username: zuobiaoxi0425@163.com
    password: RUZMSVFPRFIESNSC
    host: smtp.163.com
  redis:
    port: 6379
    host: 127.0.0.1
server:
  servlet:
    context-path: /personnel
  port: 45678


email-sender:
  from: zuobiaoxi0425@163.com(拉圈圈)

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: debug