spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/personnel_salary
    username: personnel_salary
    password: personnel_salary
  mail:
    username: zuobiaoxi0425@163.com
    password: RUZMSVFPRFIESNSC
    host: smtp.163.com
  redis:
    port: 6379
    host: 192.168.56.101
server:
  servlet:
    context-path: /personnel
  port: 45678


email-sender:
  from: zuobiaoxi0425@163.com(拉圈圈)

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: debug